---
apiVersion: v1
kind: Service

metadata:
  name: benchmarker-service

spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.1.71

  ports:
  - port: 8081
    targetPort: 80

  selector:
    app: benchmarker
