---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: <DEPLOYMENT_NAME>

spec:
  replicas: <SERVICE_REPLICAS>
  selector:
    matchLabels:
      app: <DEPLOYMENT_NAME>

  template:
    metadata:
      labels:
        app: <DEPLOYMENT_NAME>

    spec:
      containers:
      - name: <DEPLOYMENT_NAME>
        image: <IMAGE_NAME>
        ports:
        - containerPort: <SERVICE_INTERNAL_PORT>
