---
apiVersion: v1
kind: Service

metadata:
  name: exposer-service

spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.1.71

  ports:
  - port: 80
    targetPort: 80

  selector:
    app: exposer
