---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: forecaster

spec:
  replicas: 4
  selector:
    matchLabels:
      app: forecaster

  template:
    metadata:
      labels:
        app: forecaster

    spec:
      containers:
      - name: forecaster
        image: docker.io/lozioo/forecaster:latest
        ports:
        - containerPort: 80

        env:
        - name: OPENSTACK_CONTAINER
          value: https://swift.cloud.garr.it/swift/v1/ds-bucket/
