---
- name: "Kubernetes master provisioning"
  hosts: master
  become: true

  tasks:
    - name: "Reading setup_kube/kube_key.pem.pub"
      become_user: "{{ ansible_user }}"
      register: kube_key
      ansible.builtin.slurp:
        path: "~/{{ repo_name }}/setup_kube/kube_key.pem.pub"

    - name: "Adding kube_key.pem.pub to authorized_keys"
      become_user: "{{ ansible_user }}"
      ansible.builtin.lineinfile:
        path: "~/.ssh/authorized_keys"
        line: "{{ kube_key.content | b64decode | trim }}"
        state: present
        create: true
        mode: "0o600"

    - name: "Booting Kubernetes master"
      changed_when: false
      ansible.builtin.command:
        chdir: "/home/{{ ansible_user }}/{{ repo_name }}/setup_kube"
        cmd: "./boot_master.sh"
